### ISSUE TITLE
2.x 之后的 mybatis 执行 insert 后不会返回主键

### ISSUE THREAD

**Issue by ziyoung** [digitalsonic/geektime-spring-family#11]
Mabatis 3.5.0（mybatis-spring-boot-starter 2.x） 之后使用 useGeneratedKeys 时要设置 keyProperty。相关 pr https://github.com/mybatis/mybatis-3/pull/1198

> 因为 demo 中使用是 1.3.x mybatis-spring-boot-starter 所以不会出现该问题。

**Comment by ziyoung** [comment]
添加 keyProperty 即可。如果有必要，我可以提交一个 pr。

**Comment by digitalsonic** [comment]
我已经提交了更新，加上这个属性了，谢谢。
